version: '2'
services:
  game:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./src:/home/node/app/src"
      - "./public:/home/node/app/public"
      - "./package.json:/home/node/app/package.json"
